### ISSUE TITLE
Create Postgres db as docker container with docker-compose.yml file

### ISSUE THREAD

**Issue by jp2703** [OskarWiedeweg/TitanicProbability#10]
```
version: "3"

services:
  titanic-db:
    image: postgres:12.1
    volumes:
      - titanic-data:/var/lib/postgresql/titanic
    environment:
      - POSTGRES_USER=titanicuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=titanic
    ports:
      - "5432:5432"
    networks: ['titanic-network']

volumes:
  titanic-data:

networks: {titanic: {}}
```

After creating postgres db connect application to postgres-db
